name: Build Ska Package
description: "A Github Action to build a Ska3 package."
author: Javier G Gonzalez
inputs:
  repository:
    description: Repository to build from
    required: false
    type: string
    default: ${GITHUB_REPOSITORY}
  tag:
    description: tag/ref/commit-sha
    required: false
    type: string
    default: ${GITHUB_SHA}
  noarch:
    description: Does not build arch-specific packages
    required: false
    type: boolean
    default: false
  python_version:
    description: Python version
    required: false
    type: string
    default: "3.10"
  numpy_version:
    description: Numpy version
    required: false
    type: string
    default: "1.21"
  miniconda_version:
    description: Miniconda version
    required: false
    type: string
    default: py39_4.12.0
  skare3_branch:
    description: Branch of skare3
    required: false
    type: string
    default: master
  channel:
    description: Ska Conda channel
    required: false
    type: string
    default: flight
  CONDA_PASSWORD:
    required: true
  CHANDRA_XRAY_TOKEN:
    required: true
  token:
    required: true
branding:
  color: "black"
  icon: "code"

runs:
  using: "composite"
  steps:
  - name: Fetch
    uses: actions/checkout@v3
    shell: bash -l {0}
  - name: Show Inputs
    if: ${{ (matrix.os == 'ubuntu-latest') || !inputs.noarch }}
    shell: bash -l {0}
    run: |
      echo OS: ${{ matrix.os }}
      echo repository: \'${{ inputs.repository }}\'
      echo tag: \'${{ inputs.tag }}\'
      echo noarch: \'${{ inputs.noarch }}\'
      echo python_version: \'${{ inputs.python_version }}\'
      echo numpy_version: \'${{ inputs.numpy_version }}\'
      echo miniconda_version: \'${{ inputs.miniconda_version }}\'
      echo skare3_branch: \'${{ inputs.skare3_branch }}\'
      echo CONDA_PASSWORD: \'${{ inputs.CONDA_PASSWORD }}\'
      echo CHANDRA_XRAY_TOKEN: \'${{ inputs.CHANDRA_XRAY_TOKEN }}\'
      echo token: \'${{ inputs.token }}\'
  - name: Fetch Skare3
    uses: actions/checkout@v3
    shell: bash -l {0}
    with:
      repository: sot/skare3
      ref: ${{ inputs.skare3_branch }}
      path: skare3

